package exercises.config

object CurrentPrincipalsComplexConfig {
  val jsonPath: Map[String, String] = Map.apply(
    "Former_Principal_Association_Start_Date" -> "organization.formerPrincipals.associationStartDate",
    "currentprincipals_disqualifications_dataprovider_code_1" -> "organization.currentPrincipals.disqualifications.dataProvider.dnbCode",
    "formerprincipals_birthdate" -> "organization.formerPrincipals.birthDate",
    "formerprincipals_primaryaddr_addrlocality_name" -> "organization.formerPrincipals.primaryAddress.addressLocality.name",
    "currentprincipals_namesuffix" -> "organization.currentPrincipals.nameSuffix",
    "currentprincipals_disqualifications_dataprovider_desc_2" -> "organization.currentPrincipals.disqualifications.dataProvider.description",
    "Current_Principal_Other_Language_Name_First_Name" -> "organization.currentPrincipals.otherLanguageNames.givenName",
    "currentprincipals_primaryaddr_addrlocality_name" -> "organization.currentPrincipals.primaryAddress.addressLocality.name",
    "currentprincipals_nationality_name" -> "organization.currentPrincipals.nationality.name",
    "formerprincipals_primaryaddr_addrregion_name" -> "organization.formerPrincipals.primaryAddress.addressRegion.name",
    "currentprincipals_familyname" -> "organization.currentPrincipals.familyName",
    "currentprincipals_primaryaddr_postofficebox_typedesc" -> "organization.currentPrincipals.primaryAddress.postOfficeBox.typeDescription",
    "formerprincipals_primaryaddr_street_line2" -> "organization.formerPrincipals.primaryAddress.streetAddress.line2",
    "currentprincipals_disqualifications_disqualificationtype_desc_1" -> "organization.currentPrincipals.disqualifications.disqualificationType.description",
    "formerprincipals_namesuffix" -> "organization.formerPrincipals.nameSuffix",
    "currentprincipals_disqualifications_startdate_3" -> "organization.currentPrincipals.disqualifications.startDate",
    "Curr_Princ_Start_Date" -> "organization.currentPrincipals.associationStartDate",
    "formerprincipals_responsibleareas_desc" -> "organization.formerPrincipals.responsibleAreas.description",
    "Current_Principal_Other_Language_Name_Last_Name" -> "organization.currentPrincipals.otherLanguageNames.familyName",
    "currentprincipals_primaryaddr_county_name" -> "organization.currentPrincipals.primaryAddress.addressCounty.name",
    "currentprincipals_disqualifications_acttext_1" -> "organization.currentPrincipals.disqualifications.actText",
    "formerprincipals_middlename" -> "organization.formerPrincipals.middleName",
    "formerprincipals_primaryaddr_postalcodeposition_code" -> "organization.formerPrincipals.primaryAddress.postalCodePosition.dnbCode",
    "Current_Principal_Telephone_Number" -> "organization.currentPrincipals.telephones.telephoneNumber",
    "currentprincipals_disqualifications_disqualificationtype_code_3" -> "organization.currentPrincipals.disqualifications.disqualificationType.dnbCode",
    "currentprincipals_disqualifications_dataprovider_code_2" -> "organization.currentPrincipals.disqualifications.dataProvider.dnbCode",
    "currentprincipals_primaryaddr_postofficebox_postofficeboxnumber" -> "organization.currentPrincipals.primaryAddress.postOfficeBox.postOfficeBoxNumber",
    "primaryname" -> "organization.primaryName",
    "currentprincipals_disqualifications_disqualificationtype_desc_3" -> "organization.currentPrincipals.disqualifications.disqualificationType.description",
    "currentprincipals_disqualifications_dataprovider_desc_3" -> "organization.currentPrincipals.disqualifications.dataProvider.description",
    "currentprincipals_disqualifications_enddate_1" -> "organization.currentPrincipals.disqualifications.endDate",
    "formerprincipals_primaryaddr_postofficebox_typedesc" -> "organization.formerPrincipals.primaryAddress.postOfficeBox.typeDescription",
    "currentprincipals_primaryaddr_postalcode" -> "organization.currentPrincipals.primaryAddress.postalCode",
    "formerprincipals_jobtitles_title" -> "organization.formerPrincipals.jobTitles.title",
    "currentprincipals_primaryaddr_country_isoalpha2code" -> "organization.currentPrincipals.primaryAddress.addressCountry.isoAlpha2Code",
    "currentprincipals_idnumbers_idnumber" -> "organization.currentPrincipals.idNumbers.idNumber",
    "formerprincipals_primaryaddr_postofficebox_typecode" -> "organization.formerPrincipals.primaryAddress.postOfficeBox.typeDnBCode",
    "currentprincipals_disqualifications_startdate_2" -> "organization.currentPrincipals.disqualifications.startDate",
    "countryisoalpha2code" -> "organization.countryISOAlpha2Code",
    "currentprincipals_disqualifications_acttype_desc_1" -> "organization.currentPrincipals.disqualifications.actType.description",
    "currentprincipals_disqualifications_disqualificationtype_desc_2" -> "organization.currentPrincipals.disqualifications.disqualificationType.description",
    "currentprincipals_disqualifications_dataprovider_code_3" -> "organization.currentPrincipals.disqualifications.dataProvider.dnbCode",
    "formerprincipals_primaryaddr_postofficebox_postofficeboxnumber" -> "organization.formerPrincipals.primaryAddress.postOfficeBox.postOfficeBoxNumber",
    "currentprincipals_primaryaddr_street_line1" -> "organization.currentPrincipals.primaryAddress.streetAddress.line1",
    "formerprincipals_idnumbers_idnumber" -> "organization.formerPrincipals.idNumbers.idNumber",
    "formerprincipals_primaryaddr_street_line1" -> "organization.formerPrincipals.primaryAddress.streetAddress.line1",
    "formerprincipals_idnumbers_idtype_desc" -> "organization.formerPrincipals.idNumbers.idType.description",
    "currentprincipals_disqualifications_acttext_2" -> "organization.currentPrincipals.disqualifications.actText",
    "formerprincipals_managementresponsibilities_mrccode" -> "organization.formerPrincipals.managementResponsibilities.mrcCode",
    "currentprincipals_primaryaddr_country_name" -> "organization.currentPrincipals.primaryAddress.addressCountry.name",
    "currentprincipals_managementresponsibilities_desc" -> "organization.currentPrincipals.managementResponsibilities.description",
    "currentprincipals_primaryaddr_addrregion_name" -> "organization.currentPrincipals.primaryAddress.addressRegion.name",
    "currentprincipals_issigningauthority" -> "organization.currentPrincipals.isSigningAuthority",
    "currentprincipals_idnumbers_idtype_code" -> "organization.currentPrincipals.idNumbers.idType.dnbCode",
    "formerprincipals_managementresponsibilities_desc" -> "organization.formerPrincipals.managementResponsibilities.description",
    "currentprincipals_primaryaddr_postalcodeposition_code" -> "organization.currentPrincipals.primaryAddress.postalCodePosition.dnbCode",
    "formerprincipals_fullname" -> "organization.formerPrincipals.fullName",
    "currentprincipals_gender_desc" -> "organization.currentPrincipals.gender.description",
    "Former_Principal_Association_End_Date" -> "organization.formerPrincipals.associationEndDate",
    "currentprincipals_disqualifications_disqualificationtype_code_2" -> "organization.currentPrincipals.disqualifications.disqualificationType.dnbCode",
    "formerprincipals_subjecttype_desc" -> "organization.formerPrincipals.subjectType.description",
    "currentprincipals_associations_startdate_11" -> "organization.currentPrincipals.associations.startDate",
    "currentprincipals_disqualifications_acttype_code_1" -> "organization.currentPrincipals.disqualifications.actType.dnbCode",
    "formerprincipals_nameprefix" -> "organization.formerPrincipals.namePrefix",
    "currentprincipals_disqualifications_acttype_desc_2" -> "organization.currentPrincipals.disqualifications.actType.description",
    "currentprincipals_associations_duns_1" -> "organization.currentPrincipals.associations.duns",
    "formerprincipals_primaryaddr_streetname" -> "organization.formerPrincipals.primaryAddress.streetName",
    "currentprincipals_disqualifications_startdate_1" -> "organization.currentPrincipals.disqualifications.startDate",
    "formerprincipals_idnumbers_idtype_code" -> "organization.formerPrincipals.idNumbers.idType.dnbCode",
    "currentprincipals_disqualifications_enddate_2" -> "organization.currentPrincipals.disqualifications.endDate",
    "currentprincipals_primaryaddr_postalcodeposition_desc" -> "organization.currentPrincipals.primaryAddress.postalCodePosition.description",
    "formerprincipals_familyname" -> "organization.formerPrincipals.familyName",
    "currentprincipals_disqualifications_enddate_3" -> "organization.currentPrincipals.disqualifications.endDate",
    "currentprincipals_idnumbers_idtype_desc" -> "organization.currentPrincipals.idNumbers.idType.description",
    "currentprincipals_associations_duns_57" -> "organization.currentPrincipals.associations.duns",
    "formerprincipals_givenname" -> "organization.formerPrincipals.givenName",
    "currentprincipals_primaryaddr_street_line2" -> "organization.currentPrincipals.primaryAddress.streetAddress.line2",
    "duns_number" -> "organization.duns",
    "formerprincipals_primaryaddr_country_isoalpha2code" -> "organization.formerPrincipals.primaryAddress.addressCountry.isoAlpha2Code",
    "Current_Principal_Gender" -> "organization.currentPrincipals.gender",
    "currentprincipals_nameprefix" -> "organization.currentPrincipals.namePrefix",
    "currentprincipals_disqualifications_acttype_code_2" -> "organization.currentPrincipals.disqualifications.actType.dnbCode",
    "formerprincipals_primaryaddr_postalcode" -> "organization.formerPrincipals.primaryAddress.postalCode",
    "currentprincipals_managementresponsibilities_mrccode" -> "organization.currentPrincipals.managementResponsibilities.mrcCode",
    "currentprincipals_middlename" -> "organization.currentPrincipals.middleName",
    "currentprincipals_jobtitles_title" -> "organization.currentPrincipals.jobTitles.title",
    "currentprincipals_primaryaddr_streetname" -> "organization.currentPrincipals.primaryAddress.streetName",
    "currentprincipals_disqualifications_acttext_3" -> "organization.currentPrincipals.disqualifications.actText",
    "formerprincipals_primaryaddr_county_name" -> "organization.formerPrincipals.primaryAddress.addressCounty.name",
    "Current_Principal_Graduation_School_Name" -> "organization.currentPrincipals.graduationSchoolName",
    "currentprincipals_gender_code" -> "organization.currentPrincipals.gender.dnbCode",
    "currentprincipals_primaryaddr_postofficebox_typecode" -> "organization.currentPrincipals.primaryAddress.postOfficeBox.typeDnBCode",
    "currentprincipals_responsibleareas_code" -> "organization.currentPrincipals.responsibleAreas.dnbCode",
    "formerprincipals_primaryaddr_country_name" -> "organization.formerPrincipals.primaryAddress.addressCountry.name",
    "Current_Principal_Hobby_Value" -> "organization.currentPrincipals.hobbies.hobby",
    "currentprincipals_responsibleareas_desc" -> "organization.currentPrincipals.responsibleAreas.description",
    "currentprincipals_fullname" -> "organization.currentPrincipals.fullName",
    "currentprincipals_nationality_isoalpha2code" -> "organization.currentPrincipals.nationality.isoAlpha2Code",
    "currentprincipals_disqualifications_dataprovider_desc_1" -> "organization.currentPrincipals.disqualifications.dataProvider.description",
    "formerprincipals_primaryaddr_streetnumber" -> "organization.formerPrincipals.primaryAddress.streetNumber",
    "currentprincipals_disqualifications_disqualificationtype_code_1" -> "organization.currentPrincipals.disqualifications.disqualificationType.dnbCode",
    "formerprincipals_primaryaddr_postalcodeposition_desc" -> "organization.formerPrincipals.primaryAddress.postalCodePosition.description",
    "formerprincipals_nationality_isoalpha2code" -> "organization.formerPrincipals.nationality.isoAlpha2Code",
    "currentprincipals_birthdate" -> "organization.currentPrincipals.birthDate",
    "formerprincipals_responsibleareas_code" -> "organization.formerPrincipals.responsibleAreas.dnbCode",
    "currentprincipals_disqualifications_acttype_desc_3" -> "organization.currentPrincipals.disqualifications.actType.description",
    "currentprincipals_subjecttype" -> "organization.currentPrincipals.subjectType",
    "currentprincipals_disqualifications_acttype_code_3" -> "organization.currentPrincipals.disqualifications.actType.dnbCode",
    "formerprincipals_primaryaddr_minortownname" -> "organization.formerPrincipals.primaryAddress.minorTownName",
    "formerprincipals_subjecttype_code" -> "organization.formerPrincipals.subjectType.dnbCode",
    "currentprincipals_primaryaddr_continentalregion_name" -> "organization.currentPrincipals.primaryAddress.continentalRegion.name",
    "currentprincipals_primaryaddr_minortownname" -> "organization.currentPrincipals.primaryAddress.minorTownName",
    "currentprincipals_primaryaddr_streetnumber" -> "organization.currentPrincipals.primaryAddress.streetNumber",
    "formerprincipals_primaryaddr_continentalregion_name" -> "organization.formerPrincipals.primaryAddress.continentalRegion.name",
    "currentprincipals_givenname" -> "organization.currentPrincipals.givenName",
    "currentprincipals_associations_duns_1" -> "organization.currentPrincipals.associations.duns",
    "currentprincipals_associations_duns_2" -> "organization.currentPrincipals.associations.duns",
    "currentprincipals_associations_primaryname_1" -> "organization.currentPrincipals.associations.primaryName",
    "currentprincipals_associations_primaryname_2" -> "organization.currentPrincipals.associations.primaryName",
    "currentprincipals_associations_startdate_1" -> "organization.currentPrincipals.associations.startDate",
    "currentprincipals_associations_startdate_2" -> "organization.currentPrincipals.associations.startDate",
    "currentprincipals_associations_person_name_1" -> "organization.currentPrincipals.associations.person.name",
    "currentprincipals_associations_person_name_2" -> "organization.currentPrincipals.associations.person.name",
    "currentprincipals_associations_person_age_1" -> "organization.currentPrincipals.associations.person.age",
    "currentprincipals_associations_person_age_2" -> "organization.currentPrincipals.associations.person.age",
  )

  val jsonDisplayNameMap: Map[String, String] = Map.apply(
    "matchdatacriteria" -> "Match Type",
    "Former_Principal_Association_Start_Date" -> "Former Principal Association Start Date",
    "mostseniorprincipal_ade8a1ad961a4080a83823d19098a052_1" -> "Most Senior Principal Disqualification Type DNB Code Value 1",
    "currentprincipals_disqualifications_dataprovider_code_1" -> "Current Principal Disqualification Data Provider DNB Code Value 1",
    "CompanyName" -> "Company Name",
    "mostseniorprincipals_nameprefix" -> "Most Senior Principal Name Prefix",
    "matchcand_primaryaddr_country_isoalpha2code" -> "Match ISO Alpha 2 Char Country Code",
    "mostseniorprincipals_responsibleareas_code" -> "Most Senior Principals Responsible Area D&B Code",
    "mostseniorprincipal_zodiacsign_language_code_1" -> "Most Senior Principal Zodiac Sign Language Code 1",
    "mostseniorprincipal_positions_desc_4" -> "Most Senior Principal Position Text 4",
    "formerprincipals_birthdate" -> "Former Principals Birth Date",
    "matchcand_matchqualityinfo_matchdataprofile" -> "Match Data Profile",
    "mostseniorprincipals_issigningauthority" -> "Most Senior Principal Signing Authority",
    "mostseniorprincipal_positions_code_4" -> "Most Senior Principal Position Code 4",
    "formerprincipals_primaryaddr_addrlocality_name" -> "Former Principal Primary Address Locality Name",
    "mostseniorprincipal_disqualifications_startdate_1" -> "Most Senior Principal Disqualification Start Date 1",
    "currentprincipals_namesuffix" -> "Current Principal Name Suffix",
    "mostseniorprincipals_primaryaddr_country_isoalpha2code" -> "Most Senior Principal Address Country. Iso Alpha2 Code",
    "mostseniorprincipals_nationality_name" -> "Most Senior Principals Nationality",
    "mostseniorprincipals_managementresponsibilities_desc" -> "Most Senior Principal Management Responsibility Text",
    "currentprincipals_disqualifications_dataprovider_desc_2" -> "Current Principal Disqualification Data Provider Description 2",
    "mostseniorprincipals_idnumbers_idtype_desc" -> "Most Senior Principal - IDs - ID Type - Description",
    "mostseniorprincipal_hobbies_code_1" -> "Most Senior Principal Hobby Code 1",
    "Current_Principal_Other_Language_Name_First_Name" -> "Current Principal Other Language First Name",
    "currentprincipals_primaryaddr_addrlocality_name" -> "Current Principal Primary Address Locality Name",
    "mostseniorprincipals_primaryaddr_minortownname" -> "Most Senior Principals Primary Address Minor Town Name",
    "mostseniorprincipals_gender_desc" -> "Most Senior Principal Gender Text",
    "mostseniorprincipals_primaryaddr_street_line1" -> "Most Senior Principals Primary Address Street Address Line 1",
    "currentprincipals_nationality_name" -> "Current Principals Nationality",
    "formerprincipals_primaryaddr_addrregion_name" -> "Former Principal Primary Address Region Name",
    "currentprincipals_familyname" -> "Current Principal Family Name",
    "currentprincipals_primaryaddr_postofficebox_typedesc" -> "Current Principal Primary Address Post Office Box Type Description",
    "mostseniorprincipals_primaryaddr_streetname" -> "Most Senior Principals Primary Address Street Name",
    "formerprincipals_primaryaddr_street_line2" -> "Former Principal Primary Address Street Address Line 2",
    "currentprincipals_disqualifications_disqualificationtype_desc_1" -> "Current Principal Disqualification Type Description 1",
    "formerprincipals_namesuffix" -> "Former Principals Name Suffix",
    "matchcand_matchqualityinfo_matchgrade" -> "Match Grade",
    "mostseniorprincipal_positions_startdate_4" -> "Most Senior Principal Position Start Date 4",
    "mostseniorprincipal_positions_desc_3" -> "Most Senior Principal Position Text 3",
    "mostseniorprincipals_jobtitles_title" -> "Most Senior Principal Job Title",
    "mostseniorprincipals_managementresponsibilities_mrccode" -> "Most Senior Principal Management Responsibility Code",
    "Country" -> "Country",
    "currentprincipals_disqualifications_startdate_3" -> "Current Principal Disqualification Start Date 3",
    "Curr_Princ_Start_Date" -> "Current Principal Start Date",
    "formerprincipals_responsibleareas_desc" -> "Former Principals Responsible Areas Description",
    "Current_Principal_Other_Language_Name_Last_Name" -> "Current Principal Other Language Last Name",
    "mostseniorprincipal_premiselocationtype_locationtype" -> "Most Senior Principal Premise Location Type Text",
    "Unfavorable_Inactive_Associations_Count" -> "Unfavorable Inactive Associations Count",
    "currentprincipals_primaryaddr_county_name" -> "Current Principal Primary Address County Name",
    "currentprincipals_disqualifications_acttext_1" -> "Current Principal Disqualification Act 1",
    "formerprincipals_middlename" -> "Former Principals Middle Name",
    "mostseniorprincipals_nationality_isoalpha2code" -> "Most Senior Principals Nationality ISO Alpha2 Code",
    "formerprincipals_primaryaddr_postalcodeposition_code" -> "Former Principal Primary Address Postal Code Position Code",
    "Address_Street_1" -> "Street",
    "Current_Principal_Telephone_Number" -> "Current Principal Telephone Number",
    "user_customer_account_id" -> "Customer Account ID",
    "MatchErrorType" -> "Processing Error Type",
    "currentprincipals_disqualifications_disqualificationtype_code_3" -> "Current Principal Disqualification Type DNB Code Value 3",
    "currentprincipals_disqualifications_dataprovider_code_2" -> "Current Principal Disqualification Data Provider DNB Code Value 2",
    "currentprincipals_primaryaddr_postofficebox_postofficeboxnumber" -> "Current Principal Primary Address Post Office Box Number",
    "primaryname" -> "Primary Business Name",
    "mostseniorprincipal_positions_code_3" -> "Most Senior Principal Position Code 3",
    "matchcand_matchqualityinfo_namematchscore" -> "Name Match Score",
    "mostseniorprincipals_primaryaddr_postalcode" -> "Most Senior Principals Primary Address Postal Code",
    "currentprincipals_disqualifications_disqualificationtype_desc_3" -> "Current Principal Disqualification Type Description 3",
    "mostseniorprincipals_middlename" -> "Most Senior Principal Middle Name",
    "MatchErrorCode" -> "Processing Error Code",
    "currentprincipals_disqualifications_dataprovider_desc_3" -> "Current Principal Disqualification Data Provider Description 3",
    "currentprincipals_disqualifications_enddate_1" -> "Current Principal Disqualification End Date 1",
    "formerprincipals_primaryaddr_postofficebox_typedesc" -> "Former Principal Primary Address Post Office Box Desc",
    "currentprincipals_primaryaddr_postalcode" -> "Current Principal Primary Address Postal Code",
    "MatchErrorInfo" -> "Processing Error Details",
    "principalssummary_detrimentalprincipalscount" -> "Principals Detrimental Count",
    "formerprincipals_jobtitles_title" -> "Former Principals Job Titles Title",
    "mostseniorprincipal_zodiacsign_language_desc_2" -> "Most Senior Principal Zodiac Sign Language Description 2",
    "PhoneNumber" -> "Phone Number",
    "matchcand_matchqualityinfo_confidencecode" -> "Match Confidence Code",
    "currentprincipals_primaryaddr_country_isoalpha2code" -> "Current Principal Primary Address ISO Alpha 2 Char Country Code",
    "mostseniorprincipal_hobbies_desc_1" -> "Most Senior Principal Hobby Description 1",
    "Most_Senior_Principal_Bankruptcy_History_Indicator" -> "Most Senior Principal Bankruptcy History Indicator",
    "mostseniorprincipal_premiselocationtype_language_code" -> "Most Senior Principal Premise Location Type Language Code",
    "currentprincipals_idnumbers_idnumber" -> "Current Principal - IDs - ID",
    "mostseniorprincipal_positions_startdate_1" -> "Most Senior Principal Position Start Date 1",
    "mostseniorprincipal_positions_desc_2" -> "Most Senior Principal Position Text 2",
    "mostseniorprincipals_otherlanguagenames_fullname" -> "Most Senior Principal Other Languages Full Name",
    "formerprincipals_primaryaddr_postofficebox_typecode" -> "Former Principal Primary Address Post Office Box Code",
    "Most_Sr_Princ_Std_Addr_Code" -> "Most Senior Principal Primary Address - Standard Address Code",
    "mostseniorprincipals_primaryaddr_postalcodeposition_code" -> "Most Senior Principals Primary Address Postal Code Position D&B Code",
    "mostseniorprincipal_disqualifications_dataprovider_desc_2" -> "Most Senior Principal Disqualification Data Provider Description 2",
    "mostseniorprincipals_associationstartdate" -> "Most Senior Principal Start Date",
    "currentprincipals_disqualifications_startdate_2" -> "Current Principal Disqualification Start Date 2",
    "mostseniorprincipal_premiselocationtype_language_desc" -> "Most Senior Principal Premise Location Type Language Description",
    "countryisoalpha2code" -> "ISO Alpha 2 Char Country Code",
    "currentprincipals_disqualifications_acttype_desc_1" -> "Current Principal Disqualification Act Type Description 1",
    "mostseniorprincipal_zodiacsign_language_desc_1" -> "Most Senior Principal Zodiac Sign Language Description 1",
    "matchcand_primaryname" -> "Match Primary Business Name",
    "RegistrationNumber" -> "National ID",
    "mostseniorprincipals_idnumbers_idnumber" -> "Most Senior Principal - IDs - ID",
    "currentprincipals_disqualifications_disqualificationtype_desc_2" -> "Current Principal Disqualification Type Description 2",
    "currentprincipals_disqualifications_dataprovider_code_3" -> "Current Principal Disqualification Data Provider DNB Code Value 3",
    "formerprincipals_primaryaddr_postofficebox_postofficeboxnumber" -> "Former Principal Primary Address Post Office Box Number",
    "mostseniorprincipals_familyname" -> "Most Senior Principal Family Name",
    "currentprincipals_primaryaddr_street_line1" -> "Current Principal Primary Address Street Address Line 1",
    "mostseniorprincipals_fe8bc51ffb89e53e2e6a8b5e0cc67133" -> "Most Senior Principals Primary Address Post Office Box Number",
    "formerprincipals_idnumbers_idnumber" -> "Former Principal - IDs - ID",
    "mostseniorprincipal_11dae98ea7a987593e570f1e3464b11f_1" -> "Most Senior Principal Disqualification Type Description 1",
    "mostseniorprincipals_subjecttype" -> "Most Senior Principal Subject Type",
    "Address_Street_2" -> "Street Address Line 2",
    "Most_Sr_Princ_Std_Addr_Code_Type_Code" -> "Most Senior Principal Primary Address - Standard Address Code Type Code Value",
    "mostseniorprincipal_disqualifications_acttext_2" -> "Most Senior Principal Disqualification Act 2",
    "formerprincipals_primaryaddr_street_line1" -> "Former Principal Primary Address Street Address Line 1",
    "Most_Sr_Princ_Ed_Qual_Status_Description" -> "Most Senior Principal - Educational Qualification Status Description",
    "mostseniorprincipal_disqualifications_acttext_1" -> "Most Senior Principal Disqualification Act 1",
    "formerprincipals_idnumbers_idtype_desc" -> "Former Principal - IDs - ID Type - Description",
    "currentprincipals_disqualifications_acttext_2" -> "Current Principal Disqualification Act 2",
    "mostseniorprincipal_zodiacsign_language_code_2" -> "Most Senior Principal Zodiac Sign Language Code 2",
    "formerprincipals_managementresponsibilities_mrccode" -> "Former Principal Management Responsibility Code",
    "mostseniorprincipal_hobbies_desc_2" -> "Most Senior Principal Hobby Description 2",
    "mostseniorprincipal_hobbies_code_3" -> "Most Senior Principal Hobby Code 3",
    "mostseniorprincipals_givenname" -> "Most Senior Principal Given Name",
    "currentprincipals_primaryaddr_country_name" -> "Current Principal Primary Address Country/Market Name",
    "currentprincipals_managementresponsibilities_desc" -> "Current Principal Management Responsibility Text",
    "currentprincipals_primaryaddr_addrregion_name" -> "Current Principal Primary Address Region Name",
    "currentprincipals_issigningauthority" -> "Current Principal Signing Authority Indicator",
    "currentprincipals_idnumbers_idtype_code" -> "Current Principal - IDs - ID Type - Code Value",
    "mostseniorprincipals_otherlanguagenames_familyname" -> "Most Senior Principal Other Language Last Name",
    "formerprincipals_managementresponsibilities_desc" -> "Former Principal Management Responsibility Text",
    "currentprincipals_primaryaddr_postalcodeposition_code" -> "Current Principal Primary Address Postal Code Position Code",
    "Most_Sr_Princ_Std_Addr_Code_Type_Desc" -> "Most Senior Principal Primary Address - Standard Address Code Type Description",
    "mostseniorprincipals_primaryaddr_addrregion_name" -> "Most Senior Principals Primary Address Region Name",
    "formerprincipals_fullname" -> "Former Principals Full Name",
    "mostseniorprincipal_disqualifications_enddate_1" -> "Most Senior Principal Disqualification End Date 1",
    "currentprincipals_gender_desc" -> "Current Principal Gender Text",
    "currentprincipals_associations_duns_26" -> "Current Principal Associated Organization DUNS 26",
    "mostseniorprincipal_disqualifications_acttype_code_1" -> "Most Senior Principal Disqualification Act Type DNB Code Value 1",
    "Most_Senior_Principal_Birth_Address_Town_Name" -> "Most Senior Principal Birth Address Town Name",
    "Former_Principal_Association_End_Date" -> "Former Principal Association End Date",
    "currentprincipals_disqualifications_disqualificationtype_code_2" -> "Current Principal Disqualification Type DNB Code Value 2",
    "formerprincipals_subjecttype_desc" -> "Former Principal Subject Type Description",
    "mostseniorprincipals_primaryaddr_streetnumber" -> "Most Senior Principals Primary Address Street Number",
    "mostseniorprincipal_positions_desc_1" -> "Most Senior Principal Position Text 1",
    "principalssummary_detrimentalprincipalspercentage" -> "Principals Detrimental Percentage",
    "currentprincipals_disqualifications_acttype_code_1" -> "Current Principal Disqualification Act Type DNB Code Value 1",
    "mostseniorprincipal_zodiacsign_sign_1" -> "Most Senior Principal Zodiac Sign 1",
    "formerprincipals_nameprefix" -> "Former Principals Name Prefix",
    "mostseniorprincipal_positions_code_2" -> "Most Senior Principal Position Code 2",
    "currentprincipals_disqualifications_acttype_desc_2" -> "Current Principal Disqualification Act Type Description 2",
    "formerprincipals_primaryaddr_streetname" -> "Former Principal Primary Address Street Name",
    "matchcand_dunscontrolstatus_operatingstatus_desc" -> "Match Candidate Operating Status",
    "currentprincipals_disqualifications_startdate_1" -> "Current Principal Disqualification Start Date 1",
    "matchcand_duns" -> "Matched D-U-N-S Number",
    "mostseniorprincipal_ade8a1ad961a4080a83823d19098a052_2" -> "Most Senior Principal Disqualification Type DNB Code Value 2",
    "formerprincipals_idnumbers_idtype_code" -> "Former Principal - IDs - ID Type - Code Value",
    "Most_Senior_Principal_Graduation_School_Name" -> "Most Senior Principal Graduation School Name",
    "currentprincipals_disqualifications_enddate_2" -> "Current Principal Disqualification End Date 2",
    "Most_Sr_Princ_Oth_Lang_Name_Script_Dsc" -> "Most Senior Principal Name Writing Script Description",
    "DUNS" -> "DUNS Number",
    "mostseniorprincipal_disqualifications_dataprovider_code_2" -> "Most Senior Principal Disqualification Data Provider DNB Code Value 2",
    "mostseniorprincipal_positions_startdate_2" -> "Most Senior Principal Position Start Date 2",
    "Most_Sr_Princ_Oth_Lang_Name_Script_Cd" -> "Most Senior Principal Name Writing Script Code Value",
    "mostseniorprincipal_positions_code_1" -> "Most Senior Principal Position Code 1",
    "currentprincipals_primaryaddr_postalcodeposition_desc" -> "Current Principal Primary Address Postal Code Position Description",
    "formerprincipals_familyname" -> "Former Principals Family Name",
    "City" -> "City",
    "mostseniorprincipal_disqualifications_enddate_2" -> "Most Senior Principal Disqualification End Date 2",
    "currentprincipals_disqualifications_enddate_3" -> "Current Principal Disqualification End Date 3",
    "currentprincipals_idnumbers_idtype_desc" -> "Current Principal - IDs - ID Type - Description",
    "mostseniorprincipals_otherlanguagenames_givenname" -> "Most Senior Principal Other Language First Name",
    "formerprincipals_givenname" -> "Former Principals als.giv Name Mls.given Name",
    "currentprincipals_primaryaddr_street_line2" -> "Current Principal Primary Address Street Address Line 2",
    "mostseniorprincipals_birthdate" -> "Principal Birth Date",
    "mostseniorprincipals_gender_code" -> "Most Senior Principal Gender Code",
    "duns_number" -> "D-U-N-S Number",
    "formerprincipals_primaryaddr_country_isoalpha2code" -> "Former Principal Primary Address Country/Market ISO Alpha2 Code",
    "mostseniorprincipals_idnumbers_idtype_code" -> "Most Senior Principal - IDs - ID Type - Code Value",
    "Current_Principal_Gender" -> "Current Principals Gender",
    "currentprincipals_nameprefix" -> "Current Principal Name Prefix",
    "mostseniorprincipals_primaryaddr_postalcodeposition_desc" -> "Most Senior Principals Primary Address Postal Code Position Description",
    "currentprincipals_disqualifications_acttype_code_2" -> "Current Principal Disqualification Act Type DNB Code Value 2",
    "mostseniorprincipals_namesuffix" -> "Most Senior Principal Name Suffix",
    "formerprincipals_primaryaddr_postalcode" -> "Former Principal Primary Address Postal Code",
    "currentprincipals_managementresponsibilities_mrccode" -> "Current Principal Management Responsibility Code",
    "currentprincipals_middlename" -> "Current Principal Middle Name",
    "currentprincipals_jobtitles_title" -> "Current Principal Job Title",
    "mostseniorprincipals_fullname" -> "Most Senior Principal Full Name",
    "mostseniorprincipals_primaryaddr_county_name" -> "Most Senior Principals Primary Address County Name",
    "currentprincipals_primaryaddr_streetname" -> "Current Principal Primary Address Street Name",
    "Most_Senior_Principal_Telephone_Number" -> "Most Senior Principal Telephone Number",
    "currentprincipals_disqualifications_acttext_3" -> "Current Principal Disqualification Act 3",
    "mostseniorprincipal_disqualifications_dataprovider_desc_1" -> "Most Senior Principal Disqualification Data Provider Description 1",
    "Favorable_Inactive_Associations_Count" -> "Favorable Inactive Associations Count",
    "currentprincipals_associations_primaryname_153" -> "Current Principal Associated Organization Primary Name 153",
    "formerprincipals_primaryaddr_county_name" -> "Former Principal Primary Address County Name",
    "Current_Principal_Graduation_School_Name" -> "Current Principal Graduation School Name",
    "mostseniorprincipal_disqualifications_acttype_desc_1" -> "Most Senior Principal Disqualification Act Type Description 1",
    "mostseniorprincipal_zodiacsign_sign_2" -> "Most Senior Principal Zodiac Sign 2",
    "mostseniorprincipal_hobbies_desc_3" -> "Most Senior Principal Hobby Description 3",
    "currentprincipals_gender_code" -> "Current Principal Gender Code",
    "currentprincipals_primaryaddr_postofficebox_typecode" -> "Current Principal Primary Address Post Office Box Type Code",
    "mostseniorprincipal_hobbies_code_2" -> "Most Senior Principal Hobby Code 2",
    "mostseniorprincipal_disqualifications_startdate_2" -> "Most Senior Principal Disqualification Start Date 2",
    "currentprincipals_responsibleareas_code" -> "Current Principal Responsible Area DNB Code",
    "Website" -> "Website",
    "formerprincipals_primaryaddr_country_name" -> "Former Principal Primary Address Country/Market Name",
    "mostseniorprincipals_primaryaddr_country_name" -> "Most Senior Principals Primary Address Country/Market Name",
    "Most_Sr_Princ_Ed_Qual_Status_Code_Value" -> "Most Senior Principal - Educational Qualification Status Code Value",
    "mostseniorprincipals_responsibleareas_desc" -> "Most Senior Principals Responsible Area Description",
    "Most_Sr_Princ_Oth_Lang_Name_Lang_Code" -> "Most Senior Principal Name Language Code Value",
    "Most_Sr_Princ_Oth_Lang_Name_Lang_Desc" -> "Most Senior Principal Name Language Description",
    "mostseniorprincipal_disqualifications_acttype_desc_2" -> "Most Senior Principal Disqualification Act Type Description 2",
    "Current_Principal_Hobby_Value" -> "Current Principal Hobby",
    "currentprincipals_responsibleareas_desc" -> "Current Principal Responsible Areas Description",
    "mostseniorprincipals_primaryaddr_street_line2" -> "Most Senior Principals Primary Address Street Address Line 2",
    "State" -> "State",
    "currentprincipals_fullname" -> "Current Principal Full Name",
    "currentprincipals_nationality_isoalpha2code" -> "Principal Nationality ISO Alpha 2 Char Country Code",
    "mostseniorprincipals_primaryaddr_continentalregion_name" -> "Most Senior Principals Primary Address Continental Region Name",
    "currentprincipals_disqualifications_dataprovider_desc_1" -> "Current Principal Disqualification Data Provider Description 1",
    "principalssummary_inactiveassociationscount" -> "Principals Inactive Associations",
    "formerprincipals_primaryaddr_streetnumber" -> "Former Principal Primary Address Street Number",
    "currentprincipals_disqualifications_disqualificationtype_code_1" -> "Current Principal Disqualification Type DNB Code Value 1",
    "formerprincipals_primaryaddr_postalcodeposition_desc" -> "Former Principal Primary Address Postal Code Position Description",
    "mostseniorprincipal_disqualifications_acttype_code_2" -> "Most Senior Principal Disqualification Act Type DNB Code Value 2",
    "formerprincipals_nationality_isoalpha2code" -> "Former Principals Nationality ISO Alpha2 Code",
    "currentprincipals_birthdate" -> "Organization Current Principal Birth Date",
    "mostseniorprincipals_primaryaddr_postofficebox_typecode" -> "Most Senior Principals Primary Address Post Office Box Type D&B Code",
    "formerprincipals_responsibleareas_code" -> "Former Principals Responsible Areas Code",
    "Most_Senior_Principal_Educational_Qualification_Value" -> "Most Senior Principal Educational Qualification",
    "currentprincipals_disqualifications_acttype_desc_3" -> "Current Principal Disqualification Act Type Description 3",
    "currentprincipals_subjecttype" -> "Current Principal Type Text",
    "mostseniorprincipal_11dae98ea7a987593e570f1e3464b11f_2" -> "Most Senior Principal Disqualification Type Description 2",
    "mostseniorprincipals_primaryaddr_postofficebox_typedesc" -> "Most Senior Principals Primary Address Post Office Box Type Description",
    "currentprincipals_disqualifications_acttype_code_3" -> "Current Principal Disqualification Act Type DNB Code Value 3",
    "formerprincipals_primaryaddr_minortownname" -> "Former Principal Primary Address Minor Town Name",
    "formerprincipals_subjecttype_code" -> "Former Principal Subject  Type Code",
    "currentprincipals_primaryaddr_continentalregion_name" -> "Current Principal Primary Address Continental Region Name",
    "currentprincipals_primaryaddr_minortownname" -> "Current Principal Primary Address Minor Town Name",
    "mostseniorprincipal_disqualifications_dataprovider_code_1" -> "Most Senior Principal Disqualification Data Provider DNB Code Value 1",
    "mostseniorprincipal_isdisqualifieddirector" -> "Most Senior Principal Disqualified Director Indicator",
    "currentprincipals_primaryaddr_streetnumber" -> "Current Principal Primary Address Street Number",
    "mostseniorprincipals_primaryaddr_addrlocality_name" -> "Most Senior Principals Primary Address Locality Name",
    "principalssummary_currentprincipalscount" -> "Principals Current Count",
    "formerprincipals_primaryaddr_continentalregion_name" -> "Primary Address Continental Region name",
    "PostalCode" -> "Postal Code",
    "principalssummary_otherassociationscount" -> "Principals Other Associations",
    "mostseniorprincipal_positions_startdate_3" -> "Most Senior Principal Position Start Date 3",
    "currentprincipals_givenname" -> "Current Principal First Name",
    "currentprincipals_associations_duns_1" -> "Current Principal Associated Organization DUNS 1",
    "currentprincipals_associations_duns_2" -> "Current Principal Associated Organization DUNS 2",
    "currentprincipals_associations_startdate_1" -> "Current Principal Associated Start Date 1",
    "currentprincipals_associations_startdate_2" -> "Current Principal Associated Start Date 2",
    "currentprincipals_associations_primaryname_1" -> "Current Principal Associated Organization Primary Name 1",
    "currentprincipals_associations_primaryname_2" -> "Current Principal Associated Organization Primary Name 2",
    "currentprincipals_associations_person_name_1" -> "Current Principal Associated Organization Person Name 1",
    "currentprincipals_associations_person_name_2" -> "Current Principal Associated Organization Person Name 2",
    "currentprincipals_associations_person_age_1" -> "Current Principal Associated Organization Person Age 1",
    "currentprincipals_associations_person_age_2" -> "Current Principal Associated Organization Person Age 2",

  )

  val acceptedAttributeList: Seq[String] = Seq(
    "duns_number",
    "primaryname",
    "countryisoalpha2code",
    "Curr_Princ_Start_Date",
    "currentprincipals_associations_duns_1",
    "currentprincipals_associations_primaryname_1",
    "currentprincipals_associations_startdate_1",
    "currentprincipals_associations_duns_2",
    "currentprincipals_associations_primaryname_2",
    "currentprincipals_associations_startdate_2",
    "currentprincipals_associations_person_name_1",
    "currentprincipals_associations_person_name_2",
    "currentprincipals_associations_person_age_1",
    "currentprincipals_associations_person_age_2",
    "currentprincipals_birthdate",
    "currentprincipals_disqualifications_acttext_1",
    "currentprincipals_disqualifications_acttext_3",
    "currentprincipals_disqualifications_acttext_2",
    "currentprincipals_disqualifications_acttype_desc_2",
    "currentprincipals_disqualifications_acttype_desc_1",
    "currentprincipals_disqualifications_acttype_desc_3",
    "currentprincipals_disqualifications_acttype_code_3",
    "currentprincipals_disqualifications_acttype_code_1",
    "currentprincipals_disqualifications_acttype_code_2",
    "currentprincipals_disqualifications_dataprovider_desc_1",
    "currentprincipals_disqualifications_dataprovider_desc_3",
    "currentprincipals_disqualifications_dataprovider_desc_2",
    "currentprincipals_disqualifications_dataprovider_code_3",
    "currentprincipals_disqualifications_dataprovider_code_2",
    "currentprincipals_disqualifications_dataprovider_code_1",
    "currentprincipals_disqualifications_disqualificationtype_desc_1",
    "currentprincipals_disqualifications_disqualificationtype_desc_3",
    "currentprincipals_disqualifications_disqualificationtype_desc_2",
    "currentprincipals_disqualifications_disqualificationtype_code_2",
    "currentprincipals_disqualifications_disqualificationtype_code_3",
    "currentprincipals_disqualifications_disqualificationtype_code_1",
    "currentprincipals_disqualifications_enddate_1",
    "currentprincipals_disqualifications_enddate_2",
    "currentprincipals_disqualifications_enddate_3",
    "currentprincipals_disqualifications_startdate_3",
    "currentprincipals_disqualifications_startdate_2",
    "currentprincipals_disqualifications_startdate_1",
    "currentprincipals_familyname",
    "currentprincipals_fullname",
    "Current_Principal_Gender",
    "currentprincipals_gender_desc",
    "currentprincipals_gender_code",
    "currentprincipals_givenname",
    "Current_Principal_Graduation_School_Name",
    "Current_Principal_Hobby_Value",
    "currentprincipals_idnumbers_idnumber",
    "currentprincipals_idnumbers_idtype_desc",
    "currentprincipals_idnumbers_idtype_code",
    "currentprincipals_issigningauthority",
    "currentprincipals_jobtitles_title",
    "currentprincipals_managementresponsibilities_desc",
    "currentprincipals_managementresponsibilities_mrccode",
    "currentprincipals_middlename",
    "currentprincipals_nameprefix",
    "currentprincipals_namesuffix",
    "currentprincipals_nationality_isoalpha2code",
    "currentprincipals_nationality_name",
    "Current_Principal_Other_Language_Name_Last_Name",
    "Current_Principal_Other_Language_Name_First_Name",
    "currentprincipals_primaryaddr_country_isoalpha2code",
    "currentprincipals_primaryaddr_country_name",
    "currentprincipals_primaryaddr_county_name",
    "currentprincipals_primaryaddr_addrlocality_name",
    "currentprincipals_primaryaddr_addrregion_name",
    "currentprincipals_primaryaddr_continentalregion_name",
    "currentprincipals_primaryaddr_minortownname",
    "currentprincipals_primaryaddr_postofficebox_postofficeboxnumber",
    "currentprincipals_primaryaddr_postofficebox_typedesc",
    "currentprincipals_primaryaddr_postofficebox_typecode",
    "currentprincipals_primaryaddr_postalcode",
    "currentprincipals_primaryaddr_postalcodeposition_desc",
    "currentprincipals_primaryaddr_postalcodeposition_code",
    "currentprincipals_primaryaddr_street_line1",
    "currentprincipals_primaryaddr_street_line2",
    "currentprincipals_primaryaddr_streetname",
    "currentprincipals_primaryaddr_streetnumber",
    "currentprincipals_responsibleareas_desc",
    "currentprincipals_responsibleareas_code",
    "currentprincipals_subjecttype",
    "Current_Principal_Telephone_Number",
    "MatchEnrichJson"
  )

  val metadata: Map[String, Map[String, Map[Int, String]]] =
    Map("currentPrincipals_associations" -> Map(
      "primaryName" -> Map(
        0 -> "currentprincipals_associations_primaryname_1",
        1 -> "currentprincipals_associations_primaryname_2",
      ),
      "duns" -> Map(
        0 -> "currentprincipals_associations_duns_1",
        1 -> "currentprincipals_associations_duns_2",
      ),
      "startDate" -> Map(
        0 -> "currentprincipals_associations_startdate_1",
        1 -> "currentprincipals_associations_startdate_2",
      ),
      "person_name" -> Map(
        0 -> "currentprincipals_associations_person_name_1",
        1 -> "currentprincipals_associations_person_name_2",
      ),
      "person_age" -> Map(
        0 -> "currentprincipals_associations_person_age_1",
        1 -> "currentprincipals_associations_person_age_2",
      ),
    ),
      "currentPrincipals-disqualifications-actType" -> Map(
        "description" -> Map(
          0 -> "currentprincipals_disqualifications_disqualificationtype_desc_1",
          1 -> "currentprincipals_disqualifications_disqualificationtype_desc_2",
          2 -> "currentprincipals_disqualifications_disqualificationtype_desc_3")
      ),
      "currentPrincipals-disqualifications" -> Map(
        "endDate" -> Map(
          0 -> "currentprincipals_disqualifications_enddate_1",
          1 -> "currentprincipals_disqualifications_enddate_2",
          2 -> "currentprincipals_disqualifications_enddate_3"
        ),
        "actText" -> Map(
          0 -> "currentprincipals_disqualifications_acttext_1",
          1 -> "currentprincipals_disqualifications_acttext_2",
          2 -> "currentprincipals_disqualifications_acttext_3"
        ),
        "startDate" -> Map(
          0 -> "currentprincipals_disqualifications_startdate_1",
          1 -> "currentprincipals_disqualifications_startdate_2",
          2 -> "currentprincipals_disqualifications_startdate_3"
        )
      )
    )

  val sortMetadata: Map[String, Seq[(String, String)]] = Map.apply(
    "currentPrincipals_associations" -> Seq("primaryName" -> "ASC", "person.name" -> "DESC"),
    "currentPrincipals_disqualifications_actType" -> Seq("description" -> "ASC", "dnbCode" -> "ASC"),
    "currentPrincipals_disqualifications" -> Seq("endDate" -> "ASC"))
}
